name: 'On-Demand EC2 Runner'
description: 'Launch an EC2 instance on-demand to use as a GitHub Actions runner.'

# Provides metadata about the action.
author: 'evners'
branding:
  icon: 'server'
  color: 'blue'

# Defines the inputs for the action.
inputs:
  mode:
    description: 'Action mode: "start" to launch an instance, "stop" to terminate one.'
    required: false
    default: 'start'

  ec2-ami-id:
    description: >-
      AMI ID to use for the EC2 instance (e.g., ami-1234567890abcdef0)
      Input required if you use the 'start' mode.
    required: false

  ec2-min-count:
    description: Minimum number of EC2 instances to launch
    required: false
    default: '1'

  ec2-max-count:
    description: Maximum number of EC2 instances to launch
    required: false
    default: '1'

  ec2-max-wait-time:
    description: Maximum time in seconds to wait for the EC2 instance to be in "running"
    required: false
    default: '300'

  ec2-instance-type:
    description: EC2 instance type (e.g., t2.micro, t3.micro)
    required: false
    default: 't2.micro'

  github-token:
    description: GitHub Token with the 'repo' scope assigned.
    required: true

# Define how the action runs.
runs:
  using: 'node20'
  main: 'dist/index.js'
