name: 'On-Demand EC2 GitHub Runner'
description: 'Launch an EC2 instance on-demand to use as a GitHub Actions runner.'

# Provides metadata about the action.
author: 'evners'
branding:
  icon: 'server'
  color: 'blue'

# Defines the inputs for the action.
inputs:
  mode:
    description: 'Action mode: "start" to launch an instance, "stop" to terminate one.'
    required: false
    default: 'start'

  label:
    description: >-
      Label assigned to the GitHub runner, used to remove the runner from GitHub.
      Required if you use the 'stop' mode.
    required: false

  ec2-ami-id:
    description: >-
      AMI ID to use for the EC2 instance (e.g., ami-1234567890abcdef0)
      Required if you use the 'start' mode.
    required: false

  ec2-min-count:
    description: >-
      Minimum number of EC2 instances to launch
      Only used if you use the 'start' mode.
    required: false
    default: '1'

  ec2-max-count:
    description: >-
      Maximum number of EC2 instances to launch
      Only used if you use the 'start' mode.
    required: false
    default: '1'

  ec2-max-wait-time:
    description: >-
      Maximum time in seconds to wait for the EC2 instance to be in "running"
      Only used if you use the 'start' mode.
    required: false
    default: '300'

  ec2-instance-type:
    description: >-
      EC2 instance type (e.g., t2.micro, t3.micro)
      Only used if you use the 'start' mode.
    required: false
    default: 't2.micro'

  ec2-instance-id:
    description: >-
      EC2 Instance Id of the created runner, it is used to terminate the EC2 instance when the runner is not needed anymore.
      Required if you use the 'stop' mode.
    required: false

  security-group-id:
    description: >-
      Security group ID to use for the EC2 instance (e.g., sg-1234567890abcdef0)
      Only used if you use the 'start' mode.
    required: false

  subnet-id:
    description: >-
      Subnet ID to use for the EC2 instance (e.g., subnet-1234567890abcdef0)
      Only used if you use the 'start' mode.
    required: false

  github-token:
    description: GitHub Token with the 'repo' scope assigned.
    required: true

  runner-timeout-minutes:
    description: >-
      Max minutes to wait for the GitHub runner to register.
      Only used if you use the 'start' mode.
    required: false
    default: '5'

  runner-retry-seconds:
    description: >-
      Interval in seconds between checking the runner status.
      Only used if you use the 'start' mode.
    required: false
    default: '5'

  runner-quiet-seconds:
    description: 'Initial wait time (in seconds) before starting to check runner status.'
    required: false
    default: '30'

outputs:
  label:
    description: >-
      Name of the github runner, is used in two cases:
      - To use as input of 'runs-on'.
      - To remove the runner from GitHub.
  ec2-instance-id:
    description: EC2 Instance Id, used to terminate the EC2 instance.

# Define how the action runs.
runs:
  using: 'node20'
  main: 'dist/index.js'
