# Workflow to test the custom GitHub Action.
name: main

# Allow the workflow to be triggered manually.
# This is useful for testing the action.
on: workflow_dispatch

# Define the jobs that will run when the workflow is triggered.
jobs:
  start-ec2:
    # This job runs on the latest version of Ubuntu.
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout.
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Install pnpm.
      - name: Install pnpm
        run: npm install -g pnpm

      # Step 3: Install dependencies.
      - name: Install dependencies
        run: pnpm install

      # Step 4: Build the action.
      - name: Build the action
        run: pnpm build

      # Step 5: Configure AWS credentials.
      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: 'eu-west-1'
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Step 6: Create a GitHub App token.
      - name: GitHub App
        id: github-app
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.EVNERS_BOT_APP_ID }}
          private-key: ${{ secrets.EVNERS_BOT_PRIVATE_KEY }}

      # Step 7: Use the action.
      - name: On-Demand EC2
        id: start-ec2
        uses: ./
        with:
          ec2-ami-id: ami-0df368112825f8d8f
          github-token: ${{ steps.github-app.outputs.token }}
